import Link from 'next/link';import GameCard from '@/components/game/GameCard';import DailyChallenge from '@/components/game/DailyChallenge';import {questions,forDeck,localized,type Deck} from '@/lib/questions';import type {Locale} from '@/lib/i18n';import {segment} from '@/lib/i18n';
const info={
'would-you-rather':{deck:'general',h1:{en:'Would You Rather? Play Online','zh-Hant':'你寧願？線上二選一遊戲'},intro:{en:'Pick between two impossible choices, then see how your answer compares with the crowd. No account needed.','zh-Hant':'在兩個難以取捨的選項中做決定，再看看你的答案與大家有何不同，毋須建立帳戶。'}},
'would-you-rather-questions':{deck:'general',h1:{en:'Would You Rather Questions','zh-Hant':'你寧願問題大全'},intro:{en:'A curated set of funny, thoughtful and difficult dilemmas for friends, parties and quiet conversations.','zh-Hant':'精選有趣、搞笑及難以取捨的二選一問題，適合朋友聚會或輕鬆聊天。'}},
'would-you-rather-for-couples':{deck:'couples',h1:{en:'Would You Rather Questions for Couples','zh-Hant':'情侶「你寧願」二選一問題'},intro:{en:'Clean questions for date nights that reveal preferences, habits and the little things that make a relationship unique.','zh-Hant':'適合約會之夜的清新問題，從生活習慣到共同夢想，輕鬆了解彼此。'}},
'funny-would-you-rather':{deck:'funny',h1:{en:'Funny Would You Rather Questions','zh-Hant':'搞笑「你寧願」二選一問題'},intro:{en:'Ridiculous choices made to break the ice and get everyone laughing—without awkward or explicit content.','zh-Hant':'用荒誕又不尷尬的選擇打破沉默，讓朋友聚會充滿笑聲。'}},
'hard-would-you-rather':{deck:'hard',h1:{en:'Hard Would You Rather Questions','zh-Hant':'超難「你寧願」二選一問題'},intro:{en:'There is no easy way out. Weigh values, time and trade-offs, then discover where the crowd landed.','zh-Hant':'沒有容易的答案。仔細衡量價值、時間與取捨，再看看大多數人的決定。'}}} as const;
type Slug=keyof typeof info;
export default function SeoPage({locale,slug}:{locale:Locale;slug:Slug}){const x=info[slug],deck=x.deck as Deck,b=`/${segment(locale)}`,pool=slug==='would-you-rather-questions'?questions:forDeck(deck),first=localized(pool[0],locale);const zh=locale==='zh-Hant';return <main className="container py-10 md:py-16"><header className="max-w-3xl mb-8"><p className="eyebrow">Twynzo · {zh?'二選一遊戲':'Would You Rather'}</p><h1 className="mt-3">{x.h1[locale]}</h1><p className="mt-5 text-lg text-slate-600 leading-relaxed">{x.intro[locale]}</p></header><GameCard locale={locale} initial={first} initialDeck={deck}/><div className="mt-10"><DailyChallenge locale={locale}/></div><section className="mt-16"><h2>{slug==='would-you-rather-questions'?(zh?'40 個精選問題':'40 questions ready to use'):(zh?'試試這些問題':'Try a few examples')}</h2><p className="mt-3 text-slate-600">{zh?'每一題都在伺服器輸出的頁面中顯示，方便你直接閱讀及分享。':'Every question below is server-rendered, so it is easy to read, copy and share.'}</p><ol className="grid sm:grid-cols-2 gap-4 mt-7">{pool.slice(0,slug==='would-you-rather-questions'?40:10).map((q,n)=>{const z=localized(q,locale);return <li className="panel p-5" key={q.id}><span className="eyebrow">{n+1}</span><p className="font-bold mt-2">{z.a}</p><p className="text-sm my-1 text-slate-500">{zh?'或':'or'}</p><p className="font-bold">{z.b}</p></li>})}</ol></section><section className="mt-16 grid md:grid-cols-2 gap-8 prose"><div><h2>{zh?'玩法說明':'How to play'}</h2><p>{zh?'讀出兩個選項，每個人按自己的想法選一邊。Twynzo 只會在你投票後顯示真實統計，不會把多數選擇說成正確答案。':'Read both choices and pick the one you genuinely prefer. Twynzo reveals real totals only after your vote; the majority is interesting, not “correct.”'}</p></div><div><h2>{zh?'適合甚麼時候玩？':'When does it work best?'}</h2><p>{zh?'在派對、旅程、約會或朋友聊天時，用問題展開有趣對話。搞笑題適合熱身，超難題則適合深入討論。':'Use these prompts at parties, on trips, during date night or whenever conversation needs a spark. Funny decks warm up a group; hard choices invite deeper discussion.'}</p></div></section><nav aria-label="Related pages" className="mt-14 flex flex-wrap gap-3">{[['would-you-rather',zh?'開始玩':'Play'],['would-you-rather-questions',zh?'問題大全':'Question library'],['funny-would-you-rather',zh?'搞笑':'Funny'],['hard-would-you-rather',zh?'超難':'Hard'],['would-you-rather-for-couples',zh?'情侶':'Couples']].map(([s,t])=><Link className="btn bg-[#172033]!" key={s} href={`${b}/${s}/`}>{t}</Link>)}</nav></main>}
