import type {Metadata} from 'next'; import {SITE} from './site'; import type {Locale} from './i18n'; import {segment} from './i18n';
const pages={
'would-you-rather':{en:['Would You Rather Online Game – Pick a Side | Twynzo','Play Would You Rather online for free. Pick between impossible choices, compare your answers with the crowd, and try the Daily Majority Challenge.'],'zh-Hant':['你寧願？免費線上二選一遊戲 | Twynzo','免費玩 Twynzo「你寧願」二選一遊戲。做出你的選擇、看看大家怎麼選，再挑戰每日大多數預測。']},
'would-you-rather-questions':{en:['Would You Rather Questions – Funny, Hard & More | Twynzo','Discover 40 fun, thoughtful and difficult Would You Rather questions, then play them online.'],'zh-Hant':['你寧願問題大全：搞笑、超難與有趣二選一 | Twynzo','瀏覽有趣、搞笑及超難的你寧願問題，立即在線上開始二選一遊戲。']},
'would-you-rather-for-couples':{en:['Would You Rather for Couples – Fun Questions | Twynzo','Clean, thoughtful Would You Rather questions for couples, date nights and better conversations.'],'zh-Hant':['情侶你寧願問題：適合約會的二選一遊戲 | Twynzo','適合情侶和約會的有趣二選一問題，輕鬆展開好對話。']},
'funny-would-you-rather':{en:['Funny Would You Rather Questions & Game | Twynzo','Play funny Would You Rather questions made for laughs, friends and parties.'],'zh-Hant':['搞笑你寧願問題：爆笑二選一遊戲 | Twynzo','和朋友玩輕鬆搞笑的你寧願二選一問題。']},
'hard-would-you-rather':{en:['Hard Would You Rather Questions – Impossible Choices | Twynzo','Face difficult Would You Rather questions with no easy answer and compare with the crowd.'],'zh-Hant':['超難你寧願問題：最難選的二選一挑戰 | Twynzo','挑戰沒有簡單答案的超難二選一問題，再看看大家怎麼選。']}} as const;
export type Slug=keyof typeof pages;
export function metadata(locale:Locale,slug:Slug):Metadata{const [title,description]=pages[slug][locale];const path=`/${segment(locale)}/${slug}/`,other=locale==='en'?'zh-Hant':'en',otherPath=`/${segment(other)}/${slug}/`;return{title,description,alternates:{canonical:SITE+path,languages:{en:locale==='en'?SITE+path:SITE+otherPath,'zh-Hant':locale==='zh-Hant'?SITE+path:SITE+otherPath,'x-default':SITE}},openGraph:{title,description,url:SITE+path,siteName:'Twynzo',type:'website',images:[{url:`${SITE}/opengraph-image`,width:1200,height:630}]}}}
