'use client';
import {useEffect,useState} from 'react';
import type {Locale} from '@/lib/i18n';
import type {Choice} from '@/lib/game';
import {copy} from '@/lib/i18n';
import {track} from '@/lib/analytics';
import {updateStreak,type Streak} from '@/lib/streak';

type Q={id:string;a:string;b:string};
type Mark='correct'|'incorrect'|'unscored';
type Reveal={personalChoice:Choice;prediction:Choice;benchmark:Choice|null;scoreable:boolean;correct:boolean|null;currentVotes:{a:number;b:number}};
type SavedResult={date:string;score:number;total:number;grid:string;streak:number};
const resultKey='twynzo_daily_result';
const emptyStreak:Streak={lastCompletedDate:null,currentStreak:0,bestStreak:0};

function readStreak(){try{return JSON.parse(localStorage.getItem('twynzo_streak')||'null') as Streak|null||emptyStreak}catch{return emptyStreak}}

export default function DailyChallenge({locale}:{locale:Locale}){
  const c=copy[locale],[started,setStarted]=useState(false),[date,setDate]=useState(''),[qs,setQs]=useState<Q[]>([]),[i,setI]=useState(0),[personal,setPersonal]=useState<Choice|null>(null),[marks,setMarks]=useState<Mark[]>([]),[reveal,setReveal]=useState<Reveal|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<SavedResult|null>(null),[shareStatus,setShareStatus]=useState('');
  useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(resultKey)||'null') as SavedResult|null;if(x)setSaved(x)}catch{}if(location.hash.startsWith('#daily'))void start()},[]);// eslint-disable-line react-hooks/exhaustive-deps

  async function start(){setBusy(true);setError('');try{const r=await fetch(`/api/daily/challenge?locale=${locale}`,{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json() as {date:string;questions:Q[]};if(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!Array.isArray(x.questions)||x.questions.length!==10)throw 0;setDate(x.date);setQs(x.questions);setStarted(true);track('daily_start',{locale})}catch{setError(locale==='en'?"Today's challenge isn't available yet. Please try again later.":'今日挑戰暫時未能提供。請稍後再試。')}finally{setBusy(false)}}

  async function predict(prediction:Choice){if(!personal)return;setBusy(true);setError('');try{const r=await fetch('/api/daily/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({date,questionId:qs[i].id,personalChoice:personal,prediction,locale}),cache:'no-store'});if(!r.ok)throw 0;const x=await r.json() as {scoreable:boolean;correct:boolean|null;benchmark:Choice|null;currentVotes:{a:number;b:number}};const mark:Mark=!x.scoreable?'unscored':x.correct?'correct':'incorrect';setMarks(m=>[...m,mark]);setReveal({personalChoice:personal,prediction,benchmark:x.benchmark,scoreable:x.scoreable,correct:x.correct,currentVotes:x.currentVotes});track('daily_question_complete',{locale,question_number:i+1,scoreable:x.scoreable,correct:x.scoreable?x.correct??undefined:undefined})}catch{setError(c.retry)}finally{setBusy(false)}}

  function nextQuestion(){const next=i+1;setPersonal(null);setReveal(null);setI(next);if(next===10){const score=marks.filter(x=>x==='correct').length,total=marks.filter(x=>x!=='unscored').length,grid=marks.map(x=>x==='correct'?'🟩':x==='incorrect'?'🟥':'⬜').join('');const key=new Date().toLocaleDateString('en-CA'),now=updateStreak(readStreak(),key);localStorage.setItem('twynzo_streak',JSON.stringify(now));const result:SavedResult={date,score,total,grid,streak:now.currentStreak};localStorage.setItem(resultKey,JSON.stringify(result));setSaved(result);track('daily_complete',{locale,score,scoreable_questions:total,streak:now.currentStreak})}}

  const final=saved?.date===date?saved:null;
  if(final){const url=`https://twynzo.com/${locale==='en'?'en':'zh-hant'}/would-you-rather/#daily`,text=locale==='en'?`Twynzo Daily\n\n${final.score}/${final.total} crowd predictions 🎯\n\n${final.grid.slice(0,5)}\n${final.grid.slice(5)}\n\nCan you predict the crowd?\n${url}`:`Twynzo 每日挑戰\n\n大多數預測：${final.score}/${final.total} 🎯\n\n${final.grid.slice(0,5)}\n${final.grid.slice(5)}\n\n你猜得到大家會怎樣選嗎？\n${url}`;return <section id="daily" className="panel p-8 text-center"><p className="eyebrow">{locale==='en'?'Today’s result':'今日結果'}</p><h2 className="mt-2">{locale==='en'?'Daily Majority':'每日大多數挑戰'}</h2><p className="text-5xl font-black mt-6">{final.score} / {final.total}</p><p className="text-3xl tracking-wider mt-6" aria-label="Daily result grid">{final.grid.slice(0,5)}<br/>{final.grid.slice(5)}</p><p className="mt-5 font-bold">🔥 {locale==='en'?`${final.streak} day streak`:`連續挑戰 ${final.streak} 日`}</p><button className="btn mt-6" onClick={async()=>{setShareStatus('');try{if(navigator.share){track('share_click',{locale,share_method:'web_share'});await navigator.share({text})}else{track('share_click',{locale,share_method:'clipboard'});await navigator.clipboard.writeText(text);setShareStatus(locale==='en'?'Result copied':'結果已複製')}}catch(e){if((e as DOMException)?.name!=='AbortError')setShareStatus(locale==='en'?"Couldn't copy the result. Please try again.":'未能複製結果，請再試一次。')}}}>{c.share}</button>{shareStatus&&<p className="mt-3 text-sm">{shareStatus}</p>}</section>}

  if(!started)return <section id="daily" className="panel p-7 md:p-10 bg-[#eee9ff]"><p className="eyebrow">{locale==='en'?'Daily':'每日'}</p><h2 className="mt-2">{locale==='en'?'Daily Majority':'每日大多數挑戰'}</h2><p className="mt-3 text-slate-600">{locale==='en'?'Make your choice, then predict the crowd across exactly 10 questions.':'先選出自己的答案，再猜大多數人的選擇，共 10 題。'}</p><button disabled={busy} onClick={start} className="btn mt-6">{locale==='en'?'Start today’s challenge':'開始今日挑戰'}</button>{error&&<div className="mt-4"><p role="alert" className="text-red-700">{error}</p><button className="font-bold underline mt-2" onClick={start}>{locale==='en'?'Try again':'再試一次'}</button></div>}</section>;

  const q=qs[i];
  if(reveal){const total=reveal.currentVotes.a+reveal.currentVotes.b,aPct=total?Math.round(reveal.currentVotes.a/total*100):0,bPct=total?100-aPct:0,score=marks.filter(x=>x==='correct').length,den=marks.filter(x=>x!=='unscored').length,benchmarkText=reveal.benchmark?(reveal.benchmark==='A'?q.a:q.b):null;return <section id="daily" className="panel p-6 md:p-10" aria-live="polite"><div className="flex justify-between font-bold"><span>{locale==='en'?'Daily Majority':'每日大多數挑戰'}</span><span>{i+1} / 10</span></div><h2 className="text-center mt-7">{reveal.scoreable?(reveal.correct?(locale==='en'?'Correct prediction ✓':'預測正確 ✓'):(locale==='en'?'Not this time':'今次未猜中')):(locale==='en'?'Not scored':'此題不計分')}</h2>{!reveal.scoreable&&<p className="text-center mt-2 text-slate-600">{locale==='en'?'There was not a clear crowd majority before your answer.':'在你回答前，大家尚未形成明確的大多數選擇。'}</p>}<div className="grid sm:grid-cols-2 gap-4 mt-7"><div className="panel p-4"><strong>A · {aPct}%</strong><p>{q.a}</p></div><div className="panel p-4"><strong>B · {bPct}%</strong><p>{q.b}</p></div></div>{benchmarkText&&<p className="mt-5 text-center">{locale==='en'?'Crowd majority before your vote':'你投票前的大多數選擇'}: <strong>{benchmarkText}</strong></p>}<p className="mt-2 text-center">{locale==='en'?'You chose':'你自己的選擇'}: <strong>{reveal.personalChoice==='A'?q.a:q.b}</strong></p><p className="mt-2 text-center">{locale==='en'?'You predicted':'你預測大多數人會選'}: <strong>{reveal.prediction==='A'?q.a:q.b}</strong></p><p className="mt-2 text-center font-bold">{locale==='en'?'Score':'目前分數'}: {score} / {den}</p><div className="text-center"><button className="btn mt-6" onClick={nextQuestion}>{i===9?(locale==='en'?'See result':'查看結果'):c.next}</button></div></section>}

  return <section id="daily" className="panel p-6 md:p-10"><div className="flex justify-between font-bold"><span>{locale==='en'?'Daily Majority':'每日大多數挑戰'}</span><span>{i+1} / 10</span></div><h2 className="text-center mt-7">{personal?c.predict:c.choose}</h2><div className="grid sm:grid-cols-2 gap-5 mt-7">{(['A','B'] as Choice[]).map(x=><button disabled={busy} key={x} className={`answer ${x.toLowerCase()} ${personal===x?'selected':''}`} onClick={()=>personal?void predict(x):setPersonal(x)}><small className="block opacity-60">{x}</small>{x==='A'?q.a:q.b}</button>)}</div>{error&&<p role="alert" className="text-red-700 text-center mt-5">{error}</p>}</section>;
}
