'use client';
import {useEffect,useState} from 'react';import type {Locale} from '@/lib/i18n';import type {Choice} from '@/lib/game';import {copy} from '@/lib/i18n';import {track} from '@/lib/analytics';import {updateStreak,type Streak} from '@/lib/streak';
type Q={id:string;a:string;b:string};type Mark='correct'|'incorrect'|'unscored';
export default function DailyChallenge({locale}:{locale:Locale}){const c=copy[locale],[started,setStarted]=useState(false),[date,setDate]=useState(''),[qs,setQs]=useState<Q[]>([]),[i,setI]=useState(0),[personal,setPersonal]=useState<Choice|null>(null),[marks,setMarks]=useState<Mark[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[streak,setStreak]=useState(0);
useEffect(()=>{if(location.hash.startsWith('#daily'))void start()},[]);// eslint-disable-line react-hooks/exhaustive-deps
async function start(){setBusy(true);const r=await fetch(`/api/daily/challenge?locale=${locale}`);if(r.ok){const x=await r.json();setDate(x.date);setQs(x.questions);setStarted(true);track('daily_start',{locale})}setBusy(false)}
async function predict(prediction:Choice){setBusy(true);setError('');try{const r=await fetch('/api/daily/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({date,questionId:qs[i].id,personalChoice:personal,prediction,locale})});if(!r.ok)throw 0;const x=await r.json(),mark:Mark=!x.scoreable?'unscored':x.correct?'correct':'incorrect',next=[...marks,mark];setMarks(next);track('daily_question_complete',{locale,question_number:i+1,scoreable:x.scoreable});setPersonal(null);setI(i+1);if(i===9){const key=new Date().toLocaleDateString('en-CA');const old=JSON.parse(localStorage.getItem('twynzo_streak')||'{"lastCompletedDate":null,"currentStreak":0,"bestStreak":0}') as Streak;const now=updateStreak(old,key);localStorage.setItem('twynzo_streak',JSON.stringify(now));setStreak(now.currentStreak);track('daily_complete',{locale,score:next.filter(m=>m==='correct').length,scoreable_questions:next.filter(m=>m!=='unscored').length,streak:now.currentStreak})}}catch{setError(c.retry)}finally{setBusy(false)}}
if(!started)return <section id="daily" className="panel p-7 md:p-10 bg-[#eee9ff]"><p className="eyebrow">{locale==='en'?'Come back tomorrow':'明天再來'}</p><h2 className="mt-2">{locale==='en'?'Daily Majority':'每日大多數挑戰'}</h2><p className="mt-3 text-slate-600">{locale==='en'?'Make your choice, then predict the crowd across exactly 10 questions.':'先選出自己的答案，再猜大多數人的選擇，共 10 題。'}</p><button disabled={busy} onClick={start} className="btn mt-6">{locale==='en'?'Start today’s challenge':'開始今日挑戰'}</button></section>;
if(i>=10){const score=marks.filter(x=>x==='correct').length,total=marks.filter(x=>x!=='unscored').length,grid=marks.map(x=>x==='correct'?'🟩':x==='incorrect'?'🟥':'⬜').join('');const url=`https://twynzo.com/${locale==='en'?'en':'zh-hant'}/would-you-rather/#daily`,text=locale==='en'?`Twynzo Daily\n\n${score}/${total} crowd predictions 🎯\n\n${grid.slice(0,5)}\n${grid.slice(5)}\n\nCan you predict the crowd?\n${url}`:`Twynzo 每日挑戰\n\n大多數預測：${score}/${total} 🎯\n\n${grid.slice(0,5)}\n${grid.slice(5)}\n\n你猜得到大家會怎樣選嗎？\n${url}`;return <section id="daily" className="panel p-8 text-center"><p className="eyebrow">{locale==='en'?'Today’s result':'今日結果'}</p><h2 className="mt-2">{locale==='en'?'Daily Majority':'每日大多數挑戰'}</h2><p className="text-5xl font-black mt-6">{score} / {total}</p><p className="text-3xl tracking-wider mt-6" aria-label={marks.join(', ')}>{grid.slice(0,5)}<br/>{grid.slice(5)}</p><p className="mt-5 font-bold">🔥 {locale==='en'?`${streak} day streak`:`連續挑戰 ${streak} 日`}</p><button className="btn mt-6" onClick={async()=>{track('share_click',{locale,share_method:navigator.share?'web_share':'clipboard'});if(navigator.share)await navigator.share({text});else await navigator.clipboard.writeText(text)}}>{c.share}</button></section>}
const q=qs[i];return <section id="daily" className="panel p-6 md:p-10"><div className="flex justify-between font-bold"><span>{locale==='en'?'Daily Majority':'每日大多數挑戰'}</span><span>{i+1} / 10</span></div><h2 className="text-center mt-7">{personal?c.predict:c.choose}</h2><div className="grid sm:grid-cols-2 gap-5 mt-7">{(['A','B'] as Choice[]).map(x=><button disabled={busy} key={x} className={`answer ${x.toLowerCase()} ${personal===x?'selected':''}`} onClick={()=>personal?void predict(x):setPersonal(x)}><small className="block opacity-60">{x}</small>{x==='A'?q.a:q.b}</button>)}</div>{error&&<p role="alert" className="text-red-700 text-center mt-5">{error}</p>}</section>}
