'use client';
import {useCallback,useEffect,useState} from 'react';import type {Locale} from '@/lib/i18n';import {copy} from '@/lib/i18n';import type {Choice} from '@/lib/game';import type {Deck} from '@/lib/questions';import {track} from '@/lib/analytics';import {features} from '@/lib/features';
type Q={id:string;a:string;b:string};type Result={a:number;b:number;total:number;aPercent:number;bPercent:number;userChoice:Choice};
export default function GameCard({locale,initial,initialDeck='general'}:{locale:Locale;initial:Q;initialDeck?:Deck}){const c=copy[locale],[q,setQ]=useState(initial),[deck,setDeck]=useState<Deck>(initialDeck),[seen,setSeen]=useState([initial.id]),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[party,setParty]=useState(false);
useEffect(()=>{track('game_start',{locale,deck});track('question_view',{locale,deck,question_id:initial.id});if(features.party&&location.hash==='#party'){setParty(true);track('party_mode_start',{locale})}},[]);// eslint-disable-line react-hooks/exhaustive-deps
const next=useCallback(async(d=deck)=>{setBusy(true);setError('');try{const r=await fetch(`/api/questions/next?deck=${d}&locale=${locale}&exclude=${seen.join(',')}`,{cache:'no-store'});if(!r.ok)throw 0;const n=await r.json() as Q;setQ(n);setSeen(s=>[...s,n.id].slice(-40));setResult(null);track('question_view',{locale,deck:d,question_id:n.id})}catch{setError(c.retry)}finally{setBusy(false)}},[deck,locale,seen,c.retry]);
async function vote(choice:Choice){setBusy(true);setError('');try{const r=await fetch('/api/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({questionId:q.id,choice,locale,mode:'free'}),cache:'no-store'});if(!r.ok)throw 0;const x=await r.json() as Result;setResult(x);track('choice_submit',{locale,deck,question_id:q.id,choice});track('result_view',{locale,deck,question_id:q.id,majority_match:(choice==='A'?x.a:x.b)>=Math.max(x.a,x.b)})}catch{setError(c.retry)}finally{setBusy(false)}}
function change(d:Deck){setDeck(d);track('deck_change',{locale,deck:d});void next(d)}
return <section className={`panel p-5 md:p-9 ${party?'fixed inset-0 z-50 rounded-none! overflow-auto grid content-center bg-[#fffaf2]':''}`} aria-live="polite"><div className="flex flex-wrap gap-3 justify-between items-center"><p className="eyebrow">{locale==='en'?'Would you rather…':'你寧願……'}</p>{features.party&&<button className="text-sm font-bold underline" onClick={()=>{if(party){setParty(false);history.replaceState(null,'',location.pathname);track('party_mode_exit',{locale})}else{setParty(true);location.hash='party';track('party_mode_start',{locale})}}}>{party?(locale==='en'?'Exit party mode':'離開派對模式'):c.party}</button>}<div className="flex gap-1" role="group" aria-label="Deck">{(['general','funny','hard','couples'] as Deck[]).map(d=><button key={d} onClick={()=>change(d)} className={`px-3 py-2 rounded-full text-sm font-bold ${deck===d?'bg-[#172033] text-white':'bg-slate-100'}`}>{locale==='en'?({general:'General',funny:'Funny',hard:'Hard',couples:'Couples'}[d]):({general:'綜合',funny:'搞笑',hard:'超難',couples:'情侶'}[d])}</button>)}</div></div><div className="grid md:grid-cols-[1fr_auto_1fr] gap-5 items-center mt-7"><Answer letter="A" text={q.a} percent={result?.aPercent} selected={result?.userChoice==='A'} disabled={busy||!!result} onClick={()=>vote('A')}/><strong className="text-center">{c.or}</strong><Answer letter="B" text={q.b} percent={result?.bPercent} selected={result?.userChoice==='B'} disabled={busy||!!result} onClick={()=>vote('B')}/></div>{result&&<div className="text-center mt-7"><p className="font-bold">{result.total} {c.votes}</p>{result.total<=1&&<p className="text-slate-600 mt-1">{c.early}</p>}<button className="btn mt-5" onClick={()=>{track('next_question',{locale,deck});void next()}}>{c.next}</button></div>}{error&&<div className="text-center mt-5"><p role="alert" className="text-red-700">{error}</p><button className="font-bold underline mt-2" onClick={()=>void next()}>{locale==='en'?'Try again':'再試一次'}</button></div>}</section>}
function Answer({letter,text,percent,selected,disabled,onClick}:{letter:Choice;text:string;percent?:number;selected:boolean;disabled:boolean;onClick:()=>void}){return <button className={`answer ${letter.toLowerCase()} ${selected?'selected':''}`} disabled={disabled} onClick={onClick} aria-label={`${letter}: ${text}${percent!==undefined?`, ${Math.round(percent)} percent`:''}`}><span className="bar" style={{width:percent===undefined?'0%':`${percent}%`}}/><span className="content"><small className="block opacity-60 mb-2">{letter}</small>{text}{percent!==undefined&&<strong className="block text-2xl mt-3">{Math.round(percent)}%</strong>}</span></button>}
